AlchemyIngredients = {
    -- 🌿 Травы (Herbalism)
    [2447]  = { name = "Peacebloom" },
    [765]   = { name = "Silverleaf" },
    [2449]  = { name = "Earthroot" },
    [785]   = { name = "Mageroyal" },
    [2450]  = { name = "Briarthorn" },
    [3820]  = { name = "Stranglekelp" },
    [2453]  = { name = "Bruiseweed" },
    [3355]  = { name = "Wild Steelbloom" },
    [3369]  = { name = "Grave Moss" },
    [3356]  = { name = "Kingsblood" },
    [3357]  = { name = "Liferoot" },
    [3818]  = { name = "Fadeleaf" },
    [3821]  = { name = "Goldthorn" },
    [3358]  = { name = "Khadgar's Whisker" },
    [3819]  = { name = "Wintersbite" },
    [4625]  = { name = "Firebloom" },
    [8831]  = { name = "Purple Lotus" },
    [8836]  = { name = "Arthas' Tears" },
    [8838]  = { name = "Sungrass" },
    [8839]  = { name = "Blindweed" },
    [8845]  = { name = "Ghost Mushroom" },
    [8846]  = { name = "Gromsblood" },
    [13463] = { name = "Dreamfoil" },
    [13464] = { name = "Golden Sansam" },
    [13465] = { name = "Mountain Silversage" },
    [13466] = { name = "Plaguebloom" },
    [13467] = { name = "Icecap" },
    [13468] = { name = "Black Lotus" },

    -- 🧴 Флаконы (Vials)
    [3371]  = { name = "Empty Vial" },
    [3372]  = { name = "Leaded Vial" },
    [8925]  = { name = "Crystal Vial" },

    -- 🧩 Специальные реагенты
    [7067]  = { name = "Elemental Earth" },
    [7068]  = { name = "Elemental Fire" },
    [7070]  = { name = "Elemental Water" },
    [7082]  = { name = "Elemental Air" },
    [7077]  = { name = "Heart of Fire" },
    [7080]  = { name = "Essence of Water" },
    [7081]  = { name = "Essence of Air" },
    [12808] = { name = "Essence of Undeath" },
    [12803] = { name = "Living Essence" },

    [7971]  = { name = "Black Pearl" },
    [5637]  = { name = "Large Fang" },
    [10286] = { name = "Heart of the Wild" },
    [8153]  = { name = "Wildvine" },
    [13423] = { name = "Stonescale Oil" },

    -- Красители
    [4342]  = { name = "Purple Dye" },
    [9210]  = { name = "Ghost Dye" },
}
